baseurl = "https://nerden.de"
languageCode = "en"
title = "Random stuff"
theme = "kiss"
copyright = ""
disqusShortname = ""
googleAnalytics = "UA-126316461-1"
# Number of posts per page
Paginate = 10
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed

includeContent = true # Includes whole content in rss
authorName = "Johannes Bruederl" # Author full name
authorEmail = "johannes.bruederl@gmail.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.utterances]
enabled = false

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = ""
github = "birdayz"
email = "johannes.bruederl@gmail.com"
linkedin = "johannes-br√ºderl-325663b3"
xing = "Johannes_Bruederl"
facebook = ""
instagram = ""
codepen = ""

[params.matomoAnalytics]
siteID = 1
rootURL = "//matomo.example.com/"

[blackfriday]
hrefTargetBlank = true

[markup.goldmark.renderer]
unsafe= true